version: '3.5'

services:
  # База данных
  postgres:
    container_name: postgres
    image: postgres
    env_file: "variables.env"
    volumes:
    - ./data:/var/lib/postgresql/data
    ports:
      - 5060:5432
    restart: unless-stopped
  
  # Админка [хост:5050]
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: "variables.env"
    ports:
      - 5050:80
    restart: unless-stopped

  # Приложение
  training:
    container_name: training
    image: training
    env_file: "variables.env"
    restart: unless-stopped   
    depends_on:
      - postgres     
      - pgadmin


networks:
  default:
