version: '3.5'

services:
  # База данных
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
    - ./data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    restart: unless-stopped
  
  # Админка [хост:5050]
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    restart: unless-stopped

  # Приложение
  training:
    container_name: training
    image: training
    environment:
      DB_USER: $POSTGRES_USER
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_NAME: "traning_bot"
      TOKEN: $TOKEN
      TOKEN_FOR_GPT: $TOKEN_FOR_GPT
      BOT_ID: $BOT_ID
      DB_URL: "postgresql://{user}:{password}@{host}:{port}/{database}"
      account_id: $ACCOUNT_ID
      secret_key: $SECRET_KEY
    restart: unless-stopped   
    depends_on:
      - postgres     
      - pgadmin


networks:
  default:
